name: Workflow B
on:
  push:
    branches:
      - main

jobs:
  job-b:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Step 1
        run: echo "This is job B in workflow B, depending on build"
      # Otros pasos necesarios para el job B
